const m = type => `ADD_PROPERTY(${type})`

export const CHANGE_ADDRESS_FIELD = m('CHANGE_ADDRESS_FIELD')

export const MANUALLY_EDIT_ADDRESS = m('EDIT_ADDRESS')

export const CHANGE_DETAILS_FIELD = m('CHANGE_DETAILS_FIELD')
